spring:
  datasource:
    url: jdbc:postgresql:couch
    username: postgres
    password: 1
    driver-class: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: auto
  jersey:
    applicationPath: /shows
    type: filter

url: http://couchtuner.ch/


